# Generated by Django 3.0.3 on 2020-04-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200401_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(null=True, related_name='likes', to='network.Post'),
        ),
    ]
