# Generated by Django 3.0.3 on 2020-04-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200402_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='network.Post'),
        ),
    ]
