# Generated by Django 3.0.3 on 2020-02-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200228_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(default=1, max_length=280),
            preserve_default=False,
        ),
    ]
