# Generated by Django 3.0.3 on 2020-03-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='starting_price',
        ),
    ]
